### ISSUE TITLE
Node and Cluster

### ISSUE THREAD

**Issue by rashmirai21** [devtron-labs/devtron#269]
- [ ] Open API Spec integration during build time
- [ ] Node and Cluster should be modular
- [ ] Create Skeleton Components for Node and Cluster
- [ ] Prioritise each Component
- [ ] Write test cases
