### ISSUE TITLE
Feature: Enhance the buildx to use cache for multi arch builds. 

### ISSUE THREAD

**Issue by rupinSec** [devtron-labs/devtron#4940]
### 🔖 Feature description

Buildx is only using a cache of one architecture, due to which our building images are taking so much time to build multi-arch images. This is due to using the --cache-to=local option and pushing the cache to s3 for both AMD and ARM arch in the same location. We need to enhance the cache behaviour for buildx to push both AMD and ARM arch caches. 

### 🎤 Pitch / Usecases

For this problem statement to solve we can use --cache-to=registry or --cache-to=local but with different names for AMD and ARM. 

Can follow this GH discussion for more info https://github.com/docker/buildx/discussions/1382 and issue: https://github.com/docker/buildx/issues/1044

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

### Subtasks
- [ ] https://github.com/devtron-labs/dashboard/issues/1728
- [ ] https://github.com/devtron-labs/devtron-enterprise/issues/1001

### QA Subtasks
- [ ] Bug-1
- [ ] Bug-2
AB#9340
